### ISSUE TITLE
Fix the complex 7-11 timeouts

### ISSUE THREAD

**Issue by TomyRO** [patriques82/shrdlite-course-project#5]

**Comment by Meister-Asrael** [comment]
I don't see any timeouts, but interpretation errors. Some of them make sense, some of them should result in interpretations

**Comment by Meister-Asrael** [comment]
Not sure if its the same problem, but in the complex world, i get a "process out of memory" after 921354 visited knots for the command "put the green object under all red objects". I'm not sure if there are so many different states reachable. Do we check if a node is already visited?

**Comment by patriques82** [comment]
Do you mean in the Planner or in Astar?

**Comment by Meister-Asrael** [comment]
In Astar, line 143, I'm note sure what the code does

**Comment by Meister-Asrael** [comment]
Ah, ok, looks good...
